# Generated by Django 3.2.25 on 2024-05-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20240525_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookmark',
            new_name='bookmarks',
        ),
    ]
