# Generated by Django 3.2.25 on 2024-05-30 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookmarks',
        ),
    ]
