# Generated by Django 3.2.25 on 2024-06-05 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 7, 58, 34, 292964)),
        ),
    ]
